"""Templates for auto-generated Dockerfiles and k8s manifests."""

DOCKERFILE_BACKEND = """# Auto-generated by WorkFlow Dashboard. Build from repo root: docker build -f Dockerfile.backend .
FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt backend/
RUN pip install --no-cache-dir -r backend/requirements.txt
RUN pip install --no-cache-dir pydantic-settings 2>/dev/null || true

COPY backend/ backend/
ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

DOCKERFILE_FRONTEND = """# Auto-generated by WorkFlow Dashboard. Set NEXT_PUBLIC_API_URL at build time for backend URL.
FROM node:20-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY frontend/package.json frontend/package-lock.json* ./frontend/
RUN cd frontend && npm ci

COPY frontend/ ./frontend/
RUN cd frontend && npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/frontend/.next/standalone ./
COPY --from=builder /app/frontend/.next/static ./.next/static
COPY --from=builder /app/frontend/public ./public

EXPOSE 3000

CMD ["node", "server.js"]
"""

# Frontend at repo root (no frontend/ folder). Does not require Next.js output: 'standalone'.
DOCKERFILE_FRONTEND_ROOT = """# Auto-generated by WorkFlow Dashboard. Frontend at repo root (no frontend/ folder).
FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
"""

K8S_NAMESPACE = """apiVersion: v1
kind: Namespace
metadata:
  name: workflow-dashboard
  labels:
    app.kubernetes.io/name: workflow-dashboard
"""

K8S_BACKEND_DEPLOYMENT = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-backend
  namespace: workflow-dashboard
  labels:
    app: workflow-backend
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: workflow-backend
  template:
    metadata:
      labels:
        app: workflow-backend
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: backend
          image: ACR_REGISTRY/workflow-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: workflow-dashboard-secrets
                  key: GITHUB_CLIENT_ID
                  optional: true
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: workflow-dashboard-secrets
                  key: GITHUB_CLIENT_SECRET
                  optional: true
            - name: GITHUB_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: workflow-dashboard-secrets
                  key: GITHUB_REDIRECT_URI
                  optional: true
            - name: CORS_ORIGINS
              value: "*"
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-backend
  namespace: workflow-dashboard
  labels:
    app: workflow-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: workflow-backend
"""

K8S_FRONTEND_DEPLOYMENT = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-frontend
  namespace: workflow-dashboard
  labels:
    app: workflow-frontend
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: workflow-frontend
  template:
    metadata:
      labels:
        app: workflow-frontend
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: frontend
          image: ACR_REGISTRY/workflow-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://workflow-backend:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-frontend
  namespace: workflow-dashboard
  labels:
    app: workflow-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: workflow-frontend
"""

# Simple CD pipeline (beach-hack style): single app, inline default Dockerfile, minimal secrets.
# Secrets: AZURE_CREDENTIALS, ACR_NAME, RESOURCE_GROUP, AKS_CLUSTER
SIMPLE_CD_WORKFLOW = """name: AKS CD Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Default Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM node:18-alpine
          WORKDIR /app
          COPY package*.json ./
          RUN npm install
          COPY . .
          EXPOSE 3000
          CMD ["npm", "start"]
          EOF

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/app:latest

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \\
            --resource-group ${{ secrets.RESOURCE_GROUP }} \\
            --name ${{ secrets.AKS_CLUSTER }} \\
            --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl create deployment app --image=${{ secrets.ACR_NAME }}.azurecr.io/app:latest --dry-run=client -o yaml > deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment/app
"""
